### ISSUE TITLE
Can't sample -- invalid arguments: CudaTensor number CudaTensor number DoubleTensor CudaTensor 

### ISSUE THREAD

**Issue by dev-dude** [larspars/word-rnn#10]
Does this help? https://github.com/karpathy/char-rnn/issues/21

ubuntu@ubuntu:~/word-rnn$ th sample.lua cv/lm_lstm_epoch50.00_2.2444.t7 -gpuid -1
creating an LSTM... 

/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/nn/Linear.lua:55: invalid arguments: CudaTensor number CudaTensor number DoubleTensor CudaTensor 
expected arguments: _CudaTensor~2D_ [CudaTensor~2D] [float] CudaTensor~2D CudaTensor~2D | _CudaTensor~2D_ float [CudaTensor~2D] float CudaTensor~2D CudaTensor~2D
stack traceback:
    [C]: in function 'addmm'
    /home/ubuntu/torch/install/share/lua/5.1/nn/Linear.lua:55: in function 'func'
    ...e/ubuntu/torch/install/share/lua/5.1/nngraph/gmodule.lua:275: in function 'neteval'
    ...e/ubuntu/torch/install/share/lua/5.1/nngraph/gmodule.lua:310: in function 'forward'
    sample.lua:153: in main chunk
    [C]: in function 'dofile'
    ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406240
ubuntu@ubuntu:~/word-rnn$

**Comment by wenjiameng** [comment]
I have the same question. Did you figure out the reason?
