### ISSUE TITLE
Performance compared to Char-RNN

### ISSUE THREAD

**Issue by jroakes** [larspars/word-rnn#3]
Have you seen dramatic performance improvements for text generation using the word-based approach as compared to the character-based approach. I have not.  I am wondering what to expect.

**Comment by larspars** [comment]
The best results in academia on natural language processing tasks are generally using word-level models. I suspect though that character-level models degrade more gracefully when datasets are small. Another thing is that word-level models are a bit more of a pain to work with, as they're slower to train and require more memory.

**Comment by jroakes** [comment]
Ok.  I noticed that as my GPU broke on word_level.  Do you have any improvement plans for this codebase or can you share any papers with me on the word level models.  I am getting good results but need to get a bit closer.  Was excited about the word level, but have been disappointed that not a decent improvement over character for my purposes.  Thanks for keeping this public and sharing.

**Comment by larspars** [comment]
Not sure what you're looking for paper wise. Pick any NLP task (translation, sentiment, captioning, etc), and the best performing model will generally be word level. 

Note that you can't compare the training/test error between the word level and char level. The first measures how many words it got right, while the latter measures how many chars it got right. So char level error will almost always be lower.

There might be ways to improve memory efficiency in the Back Propagation Through Time implementation - please submit a pull request if you find an improvement!
