### ISSUE TITLE
rex_pcre error

### ISSUE THREAD

**Issue by nyaong7** [larspars/word-rnn#6]
Thank you for your wonderful job!

While I am testing your script, I found errors as below.
"/torch/install/share/lua/5.1/trepl/init.lua:383: module 'rex_pcre' not found:No LuaRocks module found for rex_pcre"
(Previously I encountered the same error for 'nn' as in the below thread, but it disappeared after reinstall nn)

So I searched web and found that I need 'lrexlib-pcre', but when I try to install it (luarocks install lrexlib-pcre), I got the following error.
"Error: Could not find expected file libpcre.a, or libpcre.so, or libpcre.so.\* for PCRE -- you may have to install PCRE 
 in your system and/or pass PCRE_DIR or PCRE_LIBDIR to the luarocks command. Example:*\* luarocks install lrexlib-pcre PCRE_DIR=/usr/local**"
So I tried with the additional parameter PCRE_DIR, it didn't work either.

Could anybody let me know how I can avoid this error?
Thank you in advance.

**Comment by nyaong7** [comment]
I installed lrexlib-2.7.1 library manually. Then the problem solved!!

**Comment by larspars** [comment]
Glad things worked out. I've updated the readme with the command I used to install it.
