### ISSUE TITLE
Ubuntu 14.04+ required for word-rnn?

### ISSUE THREAD

**Issue by randallmunroe** [larspars/word-rnn#9]
I installed every component on OS X, then noticed the note (recently added) about fbcunn being required. fbcunn claims to require Ubuntu 14.04+. Does this imply word-rnn requires Ubuntu 14.04+? 

I'll try repeating the process on a debian jessie machine and see if that's close enough. If not, I can get Ubuntu, although it will be a VM so the NVIDIA graphics card requirement worry me a little. 

If I'm not using the GPU, is fbcunn really needed? Do you have any other suggestions for how to make this work? Thank you!

**Comment by randallmunroe** [comment]
Update: I set up a VM with Ubuntu 14.04 and got everything installed fine, but training fails with "/home/randall/torch/install/share/lua/5.1/trepl/init.lua:383: cuda runtime error (38) : no CUDA-capable device is detected"

I assume this is because the underlying fbcunn requires CUDA regardless of whether you're running word-rnn in "-gpuid -1" mode. char-rnn works fine on the base machine. Is there any way to get word-rnn running on anything other than an Ubuntu 14.04+ running natively on hardware which includes an appropriate NVIDIA card?

Note: char-rnn runs fine under OS X on my laptop, but I like what you've said about about the virtues of the word approach, and would love to try your version!

**Comment by jamcar23** [comment]
The dependence of fbcunn really limits this project. What parts of fbcunn is the dev using?

**Comment by larspars** [comment]
Apologies for not getting back to you sooner (I somehow stopped getting emails for issues). 

The fbcunn dependency used to give a faster nn.LookupTable implementation. This was never truly necessary, and currently the standard implementation in Torch is even faster than the one in fbcunn. 

There's no real reason to depend on fbcunn anymore, so I've pushed commits that remove the dependency (and adds recurrent dropout, among other nice things)

**Comment by jamcar23** [comment]
Thanks for taking care of that! Fbcunn maybe faster in some cases but its dependences require ubuntu 13.04 or 14.04, which is pretty limiting.
